### PR TITLE
Use apt-proxy if available

### PR DESCRIPTION
**Pull request by penguineer**

### CODE REVIEW

**Comment by Nold360** [comment]
never used the bash sockets on my own, so if it works, it works..  

This could be simplified & i'm not quite sure if you actually need to export the variable them.
``` bash
if [ -z $APT_PROXY_PORT ] ; then
  export APT_PROXY_PORT=3142
fi
if [ -z "${HOST_IP}" ]; then
  export HOST_IP="apt-proxy"
fi
```

could become something like this:
``` bash
: "${APT_PROXY_PORT:=3142}"
: "${HOST_IP:=apt-proxy}"
```

beside this minor "improvement", it  seems pretty dope to me...

**Comment by penguineer** [comment]
> This could be simplified & i'm not quite sure if you actually need to export the variable them.
You're right, the variables should not be exported. This was needed because of the quoted shell call in line 17. I changed this to work with local variables.

> could become something like this:
> 
> ```shell
> : "${APT_PROXY_PORT:=3142}"
> : "${HOST_IP:=apt-proxy}"
> ```

Does not work on my shell?

Thanks for the feedback!

**Comment by christf** [comment]
the syntax for setting defaults is ${VARIABLE:-default}

**Comment by penguineer** [comment]
Updated, the script has become even smaller. :)

**Comment by penguineer** [comment]
Wird so an verschiedenen Stellen verfolgreich benutzt.

**Pull request merged**
