### PR TITLE
make docker start the container without arguments

### PR DESCRIPTION
**Pull request by christf**
this will build the firmware when running the docker image without arguments. if you want an interactive shell run it with /bin/bash as parameter

### CODE REVIEW

**Comment by penguineer** [comment]
Is there a reason you don't just to `make update && site/build.sh` as entrypoint?

Is it sufficient to build only the two architectures in your proposal?

**Comment by penguineer** [comment]
I propose adding https://github.com/penguineer/gluon-docker/commit/caad115767acbc8925973641591702d8d1af5659 to this PR. This adapts the README  to the new Dockerfile.

**Review by penguineer — CHANGES_REQUESTED** [review]
I'd like to see two things changed:
* Call the site/build.sh script, so the dockerfile is indepenend from (maybe version-specific) build steps
* Adapt the README.md file. There is a commit referenced in the comments.

Thanks!

**Comment by penguineer** [comment]
Oh....build failed:

```
Makefile:66: recipe for target 'prepare-target' failed
make: *** [prepare-target] Error 1
Please set GLUON_TARGET to a valid target. Gluon supports the following targets:
 * ar71xx-generic
 * ar71xx-nand
 * brcm2708-bcm2708
 * brcm2708-bcm2709
 * mpc85xx-generic
 * x86-generic
 * x86-kvm_guest
 * x86-64
 * x86-xen_domu
Makefile:66: recipe for target 'prepare-target' failed
make: *** [prepare-target] Error 1
```

Might be fixed by calling the 'site/build.sh' script?

**Comment by penguineer** [comment]
Hm... running with

```
CMD ["cd /gluon && make update && site/build.sh -y"]
```

failed as well.

**Comment by penguineer** [comment]
Gna... fails even when I enter the commands manually (like I did before.)
I'll do a run on the machine with the master branch.

Update: master branch with `/bin/bash` went through.
Further tests were deferred by my server shutting down (again) and will be continued tomorrow.

Update 2: Build from this PR also went through. Looks like issues with cached data in docker images?
Testing a build with above suggestions.

**Comment by christf** [comment]
frankly I am at a loss of what is the current status of your tests. From your second update I take that this now works for you and you would like to see https://github.com/penguineer/gluon-docker/commit/caad115767acbc8925973641591702d8d1af5659 in this PR as well. Is that correct?

**Comment by penguineer** [comment]
> frankly I am at a loss of what is the current status of your tests. From your second update I take that this now works for you and you would like to see penguineer/gluon-docker@caad115 in this PR as well. Is that correct?

Please excuse the chaos. Status:
* your PR compiled
* I'd like to see my commit included to adapt the Readme
* I'm still wondering if we should call the build script: 'CMD ["cd /gluon && make update && site/build.sh -y"]'

I tried to compile this variant, but my server seems to have overheated again. Will check tonight.

**Comment by christf** [comment]
On Wed, May 16, 2018 at 01:23:50AM -0700, Stefan Haun wrote:
>> frankly I am at a loss of what is the current status of your tests. From your second update I take that this now works for you and you would like to see penguineer/gluon-docker@caad115 in this PR as well. Is that correct?
>
>Please excuse the chaos. Status:
No problem. Kommunikation ist Glückssache...

>* your PR compiled
>* I'd like to see my commit included to adapt the Readme
>* I'm still wondering if we should call the build script: 'CMD ["cd /gluon && make update && site/build.sh -y"]'
I had this in there but was faced with an exiting build-script that 
would require debugging. I didn't put in the effort because the script 
is run with set -e and I suggested pooling our resources for biulding 
gluon with frankfurt altogether. Hence, I was planning on leaving this 
step for a later stage.

>
>I tried to compile this variant, but my server seems to have overheated again. Will check tonight.
-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Review by penguineer — APPROVED** [review]

**Comment by penguineer** [comment]
Regarding the build failures: There seems to be an issue with image caching in Docker.

**Comment by penguineer** [comment]
>> * I'm still wondering if we should call the build script: 'CMD ["cd /gluon && make update && site/build.sh -y"]'
>>
> I had this in there but was faced with an exiting build-script that
would require debugging. I didn't put in the effort because the script
is run with set -e and I suggested pooling our resources for biulding
gluon with frankfurt altogether. Hence, I was planning on leaving this
step for a later stage.

I'll merge this and add the suggestion with another PR.

**Pull request merged**
